# Travis-CI configuration

dist: bionic

services:
    - docker

language: cpp

jobs:
  include:
    - name: debian-stable
      os: linux
      env: BASE_IMAGE=geodynamics/pythia-testenv-debian-stable TEST_COVERAGE=yes PYTHON_COVERAGE=python3-coverage
    - name: debian-testing
      os: linux
      env: BASE_IMAGE=geodynamics/pythia-testenv-debian-testing TEST_COVERAGE=yes PYTHON_COVERAGE=python3-coverage
    - name: ubuntu-18.04
      os: linux
      env: BASE_IMAGE=geodynamics/pythia-testenv-ubuntu-18.04 TEST_COVERAGE=yes PYTHON_COVERAGE=python3-coverage
    - name: ubuntu-20.04
      os: linux
      env: BASE_IMAGE=geodynamics/pythia-testenv-ubuntu-20.04 TEST_COVERAGE=yes PYTHON_COVERAGE=python3-coverage
    - name: ubuntu-20.10
      os: linux
      env: BASE_IMAGE=geodynamics/pythia-testenv-ubuntu-20.10 TEST_COVERAGE=yes PYTHON_COVERAGE=python3-coverage
    - name: fedora-32
      os: linux
      env: BASE_IMAGE=geodynamics/pythia-testenv-fedora-32 TEST_COVERAGE=yes PYTHON_COVERAGE=coverage3
    - name: fedora-33
      os: linux
      env: BASE_IMAGE=geodynamics/pythia-testenv-fedora-33 TEST_COVERAGE=yes PYTHON_COVERAGE=coverage3
    - name: centos-8
      os: linux
      env: BASE_IMAGE=geodynamics/pythia-testenv-centos-8


addons:
  apt:
    packages:
      - docker-ce


# Limit number of commits in cloning (but keep enough so that 'git describe' works)
git:
  depth: 100


install:
  - docker build -t nemesis-testenv --build-arg BASE_IMAGE=$BASE_IMAGE --build-arg TEST_COVERAGE=$TEST_COVERAGE --build-arg PYTHON_COVERAGE=$PYTHON_COVERAGE --target src -f docker/nemesis-testenv .


script: 
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run $ci_env nemesis-testenv ci-config/run_test_coverage.sh
